name: Update grants from ClickHouse core

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  update_grants:
    runs-on: k8s-small
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_AUTH_PUBLIC_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run generate
        run: make generate

      - name: Check for changes
        id: diff
        run: |
          git diff pkg/resource/grantprivilege/grants.tsv
          if ! git diff-index --quiet HEAD -- pkg/resource/grantprivilege/grants.tsv; then
            echo "push_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "push_pr=false" >> "$GITHUB_OUTPUT"
          fi
          echo "branch=chore/update-grants-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        if: steps.diff.outputs.push_pr == 'true'
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: |
            pkg/resource/grantprivilege/grants.tsv
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          commit-message: "chore: update grants from ClickHouse core code"
          branch: ${{ steps.diff.outputs.branch }}
          title: "chore: update grants from ClickHouse core code"
          base: main
          body: |
            This PR updates grants from the ClickHouse core code.

            Command used: `make generate`

            Automatically generated by the update-grants workflow.
